# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image as the base image
FROM node:22-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json for installing dependencies
COPY package.json /app/package.json

# Install the dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application files
COPY . /app

# Build the TypeScript files
RUN npm run build

# Use a smaller image for the release
FROM node:22-alpine AS release

# Set the working directory in the container
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set the command to start the MCP Agent
ENTRYPOINT ["node", "dist/cli/index.js"]
